Repository FC-BE-ToyProject-Team6/KDT_Y_BE_Toy_Project3_DEV, pull requests merged in 2023-11, with the labels that each got.

#2 [fix] readme 수정
  README.md
Labels: docs, etc

#3 [feat] Reply, LikeTrip 엔티티 추가와 Member -> User로 변경
  README.md
  src/main/java/com/fastcampus/toyproject/common/BaseTimeEntity.java
  src/main/java/com/fastcampus/toyproject/domain/itinerary/entity/Lodgement.java
  src/main/java/com/fastcampus/toyproject/domain/itinerary/entity/Movement.java
  src/main/java/com/fastcampus/toyproject/domain/itinerary/entity/Stay.java
  src/main/java/com/fastcampus/toyproject/domain/liketrip/entity/LikeTrip.java
  src/main/java/com/fastcampus/toyproject/domain/member/controller/MemberController.java
  src/main/java/com/fastcampus/toyproject/domain/member/dto/MemberRequestDTO.java
  src/main/java/com/fastcampus/toyproject/domain/member/dto/MemberResponseDTO.java
  src/main/java/com/fastcampus/toyproject/domain/member/entity/Member.java
  src/main/java/com/fastcampus/toyproject/domain/member/repository/MemberRepository.java
  src/main/java/com/fastcampus/toyproject/domain/member/service/MemberService.java
  src/main/java/com/fastcampus/toyproject/domain/reply/entity/Reply.java
  src/main/java/com/fastcampus/toyproject/domain/trip/dto/TripResponse.java
  src/main/java/com/fastcampus/toyproject/domain/trip/entity/Trip.java
  src/main/java/com/fastcampus/toyproject/domain/trip/service/TripService.java
  src/main/java/com/fastcampus/toyproject/domain/user/controller/UserController.java
  src/main/java/com/fastcampus/toyproject/domain/user/dto/UserRequestDTO.java
  src/main/java/com/fastcampus/toyproject/domain/user/dto/UserResponseDTO.java
  src/main/java/com/fastcampus/toyproject/domain/user/entity/User.java
  src/main/java/com/fastcampus/toyproject/domain/user/repository/UserRepository.java
  src/main/java/com/fastcampus/toyproject/domain/user/service/UserService.java
  src/main/resources/import.sql
  src/test/java/com/fastcampus/toyproject/ToyprojectApplicationTests.java
  src/test/java/com/fastcampus/toyproject/common/util/LocationUtilTest.java
  src/test/java/com/fastcampus/toyproject/http_requests/itinerary-create.http
  src/test/java/com/fastcampus/toyproject/http_requests/itinerary-delete.http
  src/test/java/com/fastcampus/toyproject/http_requests/itinerary-update.http
  src/test/java/com/fastcampus/toyproject/http_requests/itinerary/delete/itinerary-delete-fail-1.http
  src/test/java/com/fastcampus/toyproject/http_requests/itinerary/delete/itinerary-delete-success-1.http
  src/test/java/com/fastcampus/toyproject/http_requests/itinerary/insert/itinerary-insert-fail-1.http
  src/test/java/com/fastcampus/toyproject/http_requests/itinerary/insert/itinerary-insert-fail-2.http
  src/test/java/com/fastcampus/toyproject/http_requests/itinerary/insert/itinerary-insert-fail-3.http
  src/test/java/com/fastcampus/toyproject/http_requests/itinerary/insert/itinerary-insert-success-1.http
  src/test/java/com/fastcampus/toyproject/http_requests/itinerary/insert/itinerary-insert-success-2.http
  src/test/java/com/fastcampus/toyproject/http_requests/itinerary/insert/itnerary-insert-success-3.http
  src/test/java/com/fastcampus/toyproject/http_requests/itinerary/update/itinerary-update-fail-1.http
  src/test/java/com/fastcampus/toyproject/http_requests/itinerary/update/itinerary-update-fail-2.http
  src/test/java/com/fastcampus/toyproject/http_requests/itinerary/update/itinerary-update-success-1.http
  src/test/java/com/fastcampus/toyproject/http_requests/itnerary-create2.http
  src/test/java/com/fastcampus/toyproject/http_requests/member-create-test.http
  src/test/java/com/fastcampus/toyproject/http_requests/trip-create.http
  src/test/java/com/fastcampus/toyproject/http_requests/trip-delete.http
  src/test/java/com/fastcampus/toyproject/http_requests/trip-get-all.http
  src/test/java/com/fastcampus/toyproject/http_requests/trip-get-detail.http
  src/test/java/com/fastcampus/toyproject/http_requests/trip/delete/trip-delete-fail-1.http
  src/test/java/com/fastcampus/toyproject/http_requests/trip/delete/trip-delete-success-1.http
  src/test/java/com/fastcampus/toyproject/http_requests/trip/insert/trip-insert-fail-1.http
  src/test/java/com/fastcampus/toyproject/http_requests/trip/insert/trip-insert-success-1.http
  src/test/java/com/fastcampus/toyproject/http_requests/trip/insert/trip-insert-success-2.http
  src/test/java/com/fastcampus/toyproject/http_requests/trip/select/trip-getAll-sucess-1.http
  src/test/java/com/fastcampus/toyproject/http_requests/trip/select/trip-getDetail-fail-1.http
  src/test/java/com/fastcampus/toyproject/http_requests/trip/select/trip-getDetail-success-1.http
  src/test/java/com/fastcampus/toyproject/http_requests/trip/update/trip-update-fail-1.http
  src/test/java/com/fastcampus/toyproject/http_requests/trip/update/trip-update-success-1.http
  src/test/java/com/fastcampus/toyproject/http_requests/trip2-create.http
Labels: feat, fix

#4 [feat] Mysql 데이터베이스 셋팅
  build.gradle
  src/main/resources/application.yml
  src/test/java/com/fastcampus/toyproject/common/util/LocationUtilTest.java
  src/test/java/com/fastcampus/toyproject/domain/itinerary/controller/ItineraryControllerTest.java
  src/test/java/com/fastcampus/toyproject/domain/itinerary/dto/ItineraryResponseTest.java
  src/test/java/com/fastcampus/toyproject/domain/trip/TripControllerTest.java
  src/test/java/com/fastcampus/toyproject/domain/trip/controller/TripControllerTest.java
Labels: feat, build

#5 [refactor] 엔티티 리펙토링
  src/main/java/com/fastcampus/toyproject/common/BaseTimeEntity.java
  src/main/java/com/fastcampus/toyproject/common/util/DateUtil.java
  src/main/java/com/fastcampus/toyproject/common/util/LocationUtil.java
  src/main/java/com/fastcampus/toyproject/domain/itinerary/entity/Itinerary.java
  src/main/java/com/fastcampus/toyproject/domain/itinerary/entity/Lodgement.java
  src/main/java/com/fastcampus/toyproject/domain/itinerary/entity/Movement.java
  src/main/java/com/fastcampus/toyproject/domain/itinerary/entity/Stay.java
  src/main/java/com/fastcampus/toyproject/domain/itinerary/service/ItineraryService.java
  src/main/java/com/fastcampus/toyproject/domain/liketrip/entity/LikeTrip.java
  src/main/java/com/fastcampus/toyproject/domain/reply/entity/Reply.java
  src/main/java/com/fastcampus/toyproject/domain/trip/entity/Trip.java
  src/main/java/com/fastcampus/toyproject/domain/trip/repository/TripRepository.java
  src/main/java/com/fastcampus/toyproject/domain/trip/service/TripService.java
  src/main/java/com/fastcampus/toyproject/domain/user/entity/User.java
Labels: refactor

#6 [fix] 에러 해결이 안돼서 공유용 커밋
  src/main/java/com/fastcampus/toyproject/common/BaseTimeEntity.java
  src/main/java/com/fastcampus/toyproject/domain/itinerary/controller/ItineraryController.java
  src/main/java/com/fastcampus/toyproject/domain/trip/controller/TripController.java
  src/main/java/com/fastcampus/toyproject/domain/trip/dto/TripResponse.java
  src/main/java/com/fastcampus/toyproject/domain/trip/entity/Trip.java
  src/main/java/com/fastcampus/toyproject/domain/trip/service/TripService.java
  src/main/java/com/fastcampus/toyproject/domain/user/controller/UserController.java
  src/main/java/com/fastcampus/toyproject/domain/user/dto/UserRequestDTO.java
  src/main/java/com/fastcampus/toyproject/domain/user/service/UserService.java
  src/test/java/com/fastcampus/toyproject/http_requests/itinerary/insert/trip-create.http
  src/test/java/com/fastcampus/toyproject/http_requests/user/user-create-test.http
Labels: help wanted, fix

#7 [fix] createAt 등 BaseTimeEntity가 저장되지 않는 문제 수정
  src/main/java/com/fastcampus/toyproject/common/BaseTimeEntity.java
  src/main/java/com/fastcampus/toyproject/domain/itinerary/entity/Itinerary.java
  src/main/java/com/fastcampus/toyproject/domain/itinerary/entity/ItineraryFactory.java
  src/main/java/com/fastcampus/toyproject/domain/trip/entity/Trip.java
  src/main/java/com/fastcampus/toyproject/domain/trip/service/TripService.java
  src/main/java/com/fastcampus/toyproject/domain/user/service/UserService.java
Labels: refactor, fix

#10 [feature] Spring Security 설정 및, 회원가입, 로그인
  build.gradle
  src/main/java/com/fastcampus/toyproject/config/security/SecurityUtil.java
  src/main/java/com/fastcampus/toyproject/config/security/config/CorsConfig.java
  src/main/java/com/fastcampus/toyproject/config/security/config/JwtSecurityConfig.java
  src/main/java/com/fastcampus/toyproject/config/security/config/SecurityConfig.java
  src/main/java/com/fastcampus/toyproject/config/security/filter/JwtFilter.java
  src/main/java/com/fastcampus/toyproject/config/security/jwt/JwtAccessDeniedHanlder.java
  src/main/java/com/fastcampus/toyproject/config/security/jwt/JwtAuthenticationEntryPoint.java
  src/main/java/com/fastcampus/toyproject/config/security/jwt/TokenProvider.java
  src/main/java/com/fastcampus/toyproject/domain/trip/controller/TripController.java
  src/main/java/com/fastcampus/toyproject/domain/user/controller/UserController.java
  src/main/java/com/fastcampus/toyproject/domain/user/dto/LoginDto.java
  src/main/java/com/fastcampus/toyproject/domain/user/dto/RefreshToken.java
  src/main/java/com/fastcampus/toyproject/domain/user/dto/TokenDto.java
  src/main/java/com/fastcampus/toyproject/domain/user/dto/TokenRequestDto.java
  src/main/java/com/fastcampus/toyproject/domain/user/dto/UserRequestDTO.java
  src/main/java/com/fastcampus/toyproject/domain/user/dto/UserResponseDTO.java
  src/main/java/com/fastcampus/toyproject/domain/user/entity/Authority.java
  src/main/java/com/fastcampus/toyproject/domain/user/entity/User.java
  src/main/java/com/fastcampus/toyproject/domain/user/exception/BadCredentialsException.java
  src/main/java/com/fastcampus/toyproject/domain/user/exception/ExistEmailExcpetion.java
  src/main/java/com/fastcampus/toyproject/domain/user/exception/UserEmailNotFoundException.java
  src/main/java/com/fastcampus/toyproject/domain/user/repository/RefreshTokenRepository.java
  src/main/java/com/fastcampus/toyproject/domain/user/repository/UserRepository.java
  src/main/java/com/fastcampus/toyproject/domain/user/service/UserService.java
  src/main/resources/application.yml
  src/main/resources/logback-spring.xml
Labels: feat, build

#8 [feat] 여행 이름 검색 기능 추가
  src/main/java/com/fastcampus/toyproject/domain/liketrip/entity/LikeTrip.java
  src/main/java/com/fastcampus/toyproject/domain/reply/entity/Reply.java
  src/main/java/com/fastcampus/toyproject/domain/trip/controller/TripController.java
  src/main/java/com/fastcampus/toyproject/domain/trip/repository/TripRepository.java
  src/main/java/com/fastcampus/toyproject/domain/trip/service/TripService.java
  src/main/java/com/fastcampus/toyproject/domain/user/entity/User.java
  src/test/java/com/fastcampus/toyproject/http_requests/itinerary-create.http
  src/test/java/com/fastcampus/toyproject/http_requests/itinerary-delete.http
  src/test/java/com/fastcampus/toyproject/http_requests/itinerary-update.http
  src/test/java/com/fastcampus/toyproject/http_requests/itnerary-create2.http
  src/test/java/com/fastcampus/toyproject/http_requests/trip-delete.http
  src/test/java/com/fastcampus/toyproject/http_requests/trip-get-all.http
  src/test/java/com/fastcampus/toyproject/http_requests/trip-get-detail.http
  src/test/java/com/fastcampus/toyproject/http_requests/trip/insert/trip-insert-success-3.http
  src/test/java/com/fastcampus/toyproject/http_requests/trip/insert/trip-insert-success-4.http
  src/test/java/com/fastcampus/toyproject/http_requests/trip/insert/trip-insert-success-5.http
  src/test/java/com/fastcampus/toyproject/http_requests/trip/select/trip-getAll-byKeyword-fail-1.http
  src/test/java/com/fastcampus/toyproject/http_requests/trip/select/trip-getAll-byKeyword-success-1.http
  src/test/java/com/fastcampus/toyproject/http_requests/trips-select.http
Labels: feat

#9 [fix] 기존 예외처리 개편했습니다.
  src/main/java/com/fastcampus/toyproject/common/dto/ErrorResponseDTO.java
  src/main/java/com/fastcampus/toyproject/common/exception/DefaultException.java
  src/main/java/com/fastcampus/toyproject/common/exception/DefaultExceptionCode.java
  src/main/java/com/fastcampus/toyproject/common/exception/DefaultExceptionHandler.java
  src/main/java/com/fastcampus/toyproject/common/exception/ExceptionCode.java
  src/main/java/com/fastcampus/toyproject/common/util/DateUtil.java
  src/main/java/com/fastcampus/toyproject/common/util/LocationUtil.java
  src/main/java/com/fastcampus/toyproject/domain/itinerary/dto/ItineraryRequest.java
  src/main/java/com/fastcampus/toyproject/domain/itinerary/exception/ItineraryException.java
  src/main/java/com/fastcampus/toyproject/domain/itinerary/exception/ItineraryExceptionCode.java
  src/main/java/com/fastcampus/toyproject/domain/itinerary/util/ItineraryOrderUtil.java
  src/main/java/com/fastcampus/toyproject/domain/trip/dto/TripRequest.java
  src/main/java/com/fastcampus/toyproject/domain/trip/entity/Trip.java
  src/main/java/com/fastcampus/toyproject/domain/trip/exception/TripException.java
  src/main/java/com/fastcampus/toyproject/domain/trip/exception/TripExceptionCode.java
  src/main/java/com/fastcampus/toyproject/domain/trip/service/TripService.java
  src/test/java/com/fastcampus/toyproject/domain/itinerary/util/ItineraryOrderUtilTest.java
Labels: fix

#11 [refactor] GET /trip (여행전체조회, 상세조회, 검색) 에 대한 모든 권한허용
  src/main/java/com/fastcampus/toyproject/config/security/config/SecurityConfig.java
  src/main/java/com/fastcampus/toyproject/config/security/jwt/TokenProvider.java
  src/main/java/com/fastcampus/toyproject/domain/trip/controller/TripController.java
Labels: refactor, fix

#12 [refactor] 로그인시 토큰을 쿠키에 담도록 수정
  src/main/java/com/fastcampus/toyproject/config/security/SecurityUtil.java
  src/main/java/com/fastcampus/toyproject/config/security/config/CorsConfig.java
  src/main/java/com/fastcampus/toyproject/config/security/config/JwtSecurityConfig.java
  src/main/java/com/fastcampus/toyproject/config/security/config/SecurityConfig.java
  src/main/java/com/fastcampus/toyproject/config/security/filter/JwtFilter.java
  src/main/java/com/fastcampus/toyproject/config/security/jwt/TokenProvider.java
  src/main/java/com/fastcampus/toyproject/domain/user/controller/UserController.java
Labels: refactor

#13 [feat & fix & test] 여정-여행 수정 및 테스트 코드 작성
  src/main/java/com/fastcampus/toyproject/ToyprojectApplication.java
  src/main/java/com/fastcampus/toyproject/domain/itinerary/controller/ItineraryController.java
  src/main/java/com/fastcampus/toyproject/domain/itinerary/dto/ItineraryRequest.java
  src/main/java/com/fastcampus/toyproject/domain/itinerary/dto/MovementResponse.java
  src/main/java/com/fastcampus/toyproject/domain/itinerary/entity/ItineraryFactory.java
  src/main/java/com/fastcampus/toyproject/domain/itinerary/entity/Lodgement.java
  src/main/java/com/fastcampus/toyproject/domain/itinerary/entity/Movement.java
  src/main/java/com/fastcampus/toyproject/domain/itinerary/entity/Stay.java
  src/main/java/com/fastcampus/toyproject/domain/itinerary/exception/ItineraryExceptionCode.java
  src/main/java/com/fastcampus/toyproject/domain/itinerary/service/ItineraryService.java
  src/main/java/com/fastcampus/toyproject/domain/trip/controller/TripController.java
  src/main/java/com/fastcampus/toyproject/domain/trip/entity/Trip.java
  src/main/java/com/fastcampus/toyproject/domain/trip/exception/TripExceptionCode.java
  src/main/java/com/fastcampus/toyproject/domain/trip/service/TripService.java
  src/test/java/com/fastcampus/toyproject/domain/itinerary/controller/ItineraryControllerTest.java
  src/test/java/com/fastcampus/toyproject/domain/itinerary/service/ItineraryServiceTest.java
  src/test/java/com/fastcampus/toyproject/domain/trip/service/TripServiceTest.java
  src/test/java/com/fastcampus/toyproject/http_requests/itinerary/insert/itinerary-insert-fail-1.http
  src/test/java/com/fastcampus/toyproject/http_requests/itinerary/insert/itinerary-insert-fail-2.http
  src/test/java/com/fastcampus/toyproject/http_requests/itinerary/insert/itinerary-insert-fail-3.http
  src/test/java/com/fastcampus/toyproject/http_requests/itinerary/insert/itinerary-insert-success-1.http
  src/test/java/com/fastcampus/toyproject/http_requests/itinerary/insert/itinerary-insert-success-2.http
  src/test/java/com/fastcampus/toyproject/http_requests/itinerary/insert/itnerary-insert-success-3.http
  src/test/java/com/fastcampus/toyproject/http_requests/itinerary/update/itinerary-update-fail-1.http
  src/test/java/com/fastcampus/toyproject/http_requests/itinerary/update/itinerary-update-fail-2.http
  src/test/java/com/fastcampus/toyproject/http_requests/itinerary/update/itinerary-update-success-1.http
  src/test/java/com/fastcampus/toyproject/http_requests/trip/insert/trip-insert-success-1.http
  src/test/java/com/fastcampus/toyproject/http_requests/trip/insert/trip-insert-success-2.http
  src/test/java/com/fastcampus/toyproject/http_requests/trip/select/trip-getAll-sucess-1.http
Labels: fix, test

#14 [refactor] 토큰의 값을 가져오는 UserPrincipal 객체 생성
  src/main/java/com/fastcampus/toyproject/common/exception/DefaultExceptionHandler.java
  src/main/java/com/fastcampus/toyproject/config/security/SecurityUtil.java
  src/main/java/com/fastcampus/toyproject/config/security/exception/CustomSecurityException.java
  src/main/java/com/fastcampus/toyproject/config/security/exception/SecurityExcpetionCode.java
  src/main/java/com/fastcampus/toyproject/config/security/jwt/TokenProvider.java
  src/main/java/com/fastcampus/toyproject/config/security/jwt/UserPrincipal.java
  src/main/java/com/fastcampus/toyproject/domain/user/dto/UserResponseDTO.java
  src/main/java/com/fastcampus/toyproject/domain/user/service/UserService.java
Labels: refactor

#17 [fix] Exception, RuntimeException에 대해 stacktrace출력
  src/main/java/com/fastcampus/toyproject/common/exception/DefaultExceptionHandler.java
Labels: fix

#19 [fix] 여행, 여정 CUD 시, 로그인 유저인지 확인하도록 수정
  src/main/java/com/fastcampus/toyproject/domain/itinerary/controller/ItineraryController.java
  src/main/java/com/fastcampus/toyproject/domain/itinerary/exception/ItineraryExceptionCode.java
  src/main/java/com/fastcampus/toyproject/domain/itinerary/service/ItineraryService.java
  src/main/java/com/fastcampus/toyproject/domain/trip/controller/TripController.java
  src/main/java/com/fastcampus/toyproject/domain/trip/dto/TripDetailResponse.java
  src/main/java/com/fastcampus/toyproject/domain/trip/exception/TripExceptionCode.java
  src/main/java/com/fastcampus/toyproject/domain/trip/service/TripService.java
  src/test/java/com/fastcampus/toyproject/domain/itinerary/controller/ItineraryControllerTest.java
  src/test/java/com/fastcampus/toyproject/domain/trip/TripControllerTest.java
Labels: fix

#22 [fix] 여행 삭제 부분 에러 수정
  src/main/java/com/fastcampus/toyproject/domain/itinerary/exception/ItineraryExceptionCode.java
  src/main/java/com/fastcampus/toyproject/domain/trip/controller/TripController.java
  src/main/java/com/fastcampus/toyproject/domain/trip/exception/TripExceptionCode.java
  src/test/java/com/fastcampus/toyproject/domain/trip/TripControllerTest.java
  src/test/java/com/fastcampus/toyproject/domain/trip/controller/TripControllerTest.java
Labels: fix

#27 [refactor] 여행, 여정 예외처리코드 리팩토링
  src/main/java/com/fastcampus/toyproject/common/dto/ErrorResponseDTO.java
  src/main/java/com/fastcampus/toyproject/common/exception/DefaultException.java
  src/main/java/com/fastcampus/toyproject/common/exception/DefaultExceptionCode.java
  src/main/java/com/fastcampus/toyproject/domain/itinerary/exception/ItineraryException.java
  src/main/java/com/fastcampus/toyproject/domain/itinerary/exception/ItineraryExceptionCode.java
  src/main/java/com/fastcampus/toyproject/domain/trip/exception/TripException.java
  src/main/java/com/fastcampus/toyproject/domain/trip/exception/TripExceptionCode.java
Labels: refactor

#26 [Feature] likesCount 기능 구현
  src/main/java/com/fastcampus/toyproject/domain/liketrip/service/LikeTripService.java
  src/main/java/com/fastcampus/toyproject/domain/trip/entity/Trip.java
  src/main/java/com/fastcampus/toyproject/domain/trip/service/TripService.java
Labels: feat

#29 [feat & fix] 검색어 예외처리 추가 및 여행 상세 조회시 여정 순서들 정렬되도록 했습니다.
  src/main/java/com/fastcampus/toyproject/common/exception/DefaultExceptionHandler.java
  src/main/java/com/fastcampus/toyproject/domain/itinerary/service/ItineraryService.java
  src/main/java/com/fastcampus/toyproject/domain/reply/exception/ReplyException.java
  src/main/java/com/fastcampus/toyproject/domain/trip/controller/TripController.java
  src/main/java/com/fastcampus/toyproject/domain/trip/exception/TripExceptionCode.java
  src/main/java/com/fastcampus/toyproject/domain/trip/service/TripService.java
Labels: feat, fix

#32 [Feature] User 동작 확인 및 LocationUtil 예외 처리 코드 추가
  src/main/java/com/fastcampus/toyproject/common/util/LocationUtil.java
  src/main/java/com/fastcampus/toyproject/domain/itinerary/controller/ItineraryController.java
  src/test/java/com/fastcampus/toyproject/common/util/LocationUtilTest.java
Labels: feat

#34 [refactor] 위치 정보는 DB에 저장되도록 코드 수정했습니다.
  src/main/java/com/fastcampus/toyproject/domain/itinerary/dto/LodgementResponse.java
  src/main/java/com/fastcampus/toyproject/domain/itinerary/dto/MovementResponse.java
  src/main/java/com/fastcampus/toyproject/domain/itinerary/dto/StayResponse.java
  src/main/java/com/fastcampus/toyproject/domain/itinerary/entity/ItineraryFactory.java
  src/main/java/com/fastcampus/toyproject/domain/itinerary/entity/Lodgement.java
  src/main/java/com/fastcampus/toyproject/domain/itinerary/entity/Movement.java
  src/main/java/com/fastcampus/toyproject/domain/itinerary/entity/Stay.java
  src/test/java/com/fastcampus/toyproject/domain/trip/service/TripServiceTest.java
Labels: refactor

#35 [Feature] LikeTrip Service, Repository, Controller 테스트 구현
  src/main/java/com/fastcampus/toyproject/domain/trip/entity/Trip.java
  src/test/java/com/fastcampus/toyproject/domain/liketrip/controller/LikeTripControllerTest.java
  src/test/java/com/fastcampus/toyproject/domain/liketrip/repository/LikeTripRepositoryTest.java
  src/test/java/com/fastcampus/toyproject/domain/liketrip/service/LikeTripServiceTest.java
Labels: feat

#39 [Feature] Reply Service, Repository, Controller 테스트 구현
  src/main/java/com/fastcampus/toyproject/domain/reply/dto/ReplyRequestDTO.java
  src/test/java/com/fastcampus/toyproject/domain/reply/controller/ReplyControllerTest.java
  src/test/java/com/fastcampus/toyproject/domain/reply/repository/ReplyRepositoryTest.java
  src/test/java/com/fastcampus/toyproject/domain/reply/service/ReplyServiceTest.java
Labels: feat

#40 [test & refactor] 여정 레포지토리 테스트 생성 & 댓글 등록시 공백 안되게 수정
  src/main/java/com/fastcampus/toyproject/domain/reply/controller/ReplyController.java
  src/main/java/com/fastcampus/toyproject/domain/reply/dto/ReplyRequestDTO.java
  src/test/java/com/fastcampus/toyproject/domain/itinerary/repository/ItineraryRepositoryTest.java
Labels: test

#43 [fix] 여정 삽입 : 비동기 방식으로 수정, 성능 개선 (2초 -> 0.2초)
  src/main/java/com/fastcampus/toyproject/domain/itinerary/service/ItineraryService.java
Labels: fix
